# Generated by Django 2.0.7 on 2018-10-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='spread',
            field=models.IntegerField(default=0),
        ),
    ]
