# Generated by Django 2.2.2 on 2020-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gm_updates',
            field=models.BooleanField(default=False),
        ),
    ]
