# Generated by Django 2.0.7 on 2018-10-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_game_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bracket.Region'),
            preserve_default=False,
        ),
    ]
