# Generated by Django 3.1.13 on 2022-03-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_auto_20220209_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_game_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_game_a', to='bracket.game'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_game_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_game_b', to='bracket.game'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_game_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_game_c', to='bracket.game'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_game_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_game_d', to='bracket.game'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_team_a', to='bracket.team'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_team_b', to='bracket.team'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_team_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_team_c', to='bracket.team'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_team_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_team_d', to='bracket.team'),
        ),
    ]
