# Generated by Django 3.1.13 on 2023-03-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_ehist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehist',
            name='tbracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bracket.tbracket'),
        ),
    ]
