# Generated by Django 2.1.2 on 2019-02-21 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0004_auto_20190215_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='team1_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team2_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='bracket.Team'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='bracket.Team'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='team_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_c', to='bracket.Team'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='team_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_d', to='bracket.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='spread',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
