# Generated by Django 2.1.2 on 2019-02-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0005_auto_20190221_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='e_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='orig_team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig_team_a', to='bracket.Team'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='orig_team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig_team_b', to='bracket.Team'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='orig_team_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig_team_c', to='bracket.Team'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='orig_team_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig_team_d', to='bracket.Team'),
        ),
    ]
