# Generated by Django 2.1.2 on 2019-02-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0006_auto_20190221_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tbracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bracket.Tbracket'),
        ),
    ]
