# Generated by Django 2.1.7 on 2019-03-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0007_auto_20190228_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.IntegerField(default=0),
        ),
    ]
